// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    dependencies {
        classpath(libs.json)
//        classpath(libs.androidsvgdrawable.gradle.plugin) {
//            exclude group: 'xerces'
//        }
        classpath(libs.bye.bye.jetifier)
    }
}

plugins {
    alias(libs.plugins.android.application) apply false
}

//  see: https://github.com/dipien/bye-bye-jetifier
//  enable the following line
//  then run  ./gradlew canISayByeByeJetifier -Pandroid.enableJetifier=false
//apply plugin: "com.dipien.byebyejetifier"

